version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18   # Node.js version
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - build/**        # Include all files in the 'build' directory
  discard-paths: no   # Retain directory structure in artifacts