version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18   # Node.js version
    commands:
      - npm install

  build:
    commands:
      - npm run build

# S3 configuration for artifacts
artifacts:
  type: S3
  name: facialyst-build-artifacts         # Specify a name for the artifact
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - postcss.config.cjs
    - tsconfig.json
    - tsconfig.node.json
    - vercel.json
    - vite.config.ts
  discard-paths: no                   # Optionally discard paths
  bucket-paths:
    - facialyst.codedeploy.bucket/build-artifacts   # S3 bucket and folder path
